// File menu: archives (SAZ/HAR), bodies, cURL scripts.
import { open, save } from "@tauri-apps/plugin-dialog";
import { api } from "./api";
import { get, say } from "./store";
import { buildCurl } from "./lib/http";
import { snippetBody } from "./lib/bodytext";
import { plural, t } from "./i18n";

const ARCHIVES = [
  { name: t("Session Archive"), extensions: ["saz", "har"] },
  { name: t("SAZ Session Archive"), extensions: ["saz"] },
  { name: t("HTTP Archive (HAR)"), extensions: ["har"] },
];

function stamp() {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}`;
}

async function saveArchive(ids: number[], ext: "saz" | "har") {
  if (!get().listTotal) {
    say(t("There are no sessions to save"), "error");
    return;
  }
  const path = await save({ defaultPath: `quena_${stamp()}.${ext}`, filters: ext === "saz" ? [ARCHIVES[1], ARCHIVES[2]] : [ARCHIVES[2], ARCHIVES[1]] });
  if (!path) return;
  try {
    await api.exportArchive(ids, path);
    say(ids.length ? plural(ids.length, "Saving {n} session to {path}", "Saving {n} sessions to {path}", { path }) : t("Saving all sessions to {path}", { path }));
  } catch (e) {
    say(String(e), "error");
  }
}

async function loadArchive() {
  const path = await open({ multiple: false, filters: ARCHIVES });
  if (typeof path !== "string") return;
  try {
    await api.importArchive(path);
    say(t("Loading {path}", { path }));
  } catch (e) {
    say(String(e), "error");
  }
}

export async function handleFileMenu(id: string): Promise<boolean> {
  const selected = [...get().selection].sort((a, b) => a - b);
  switch (id) {
    case "file.load":
    case "file.import-saz":
    case "file.import-har":
      await loadArchive();
      return true;
    case "file.save-all":
    case "file.export-saz":
      await saveArchive(id === "file.export-saz" && selected.length > 1 ? selected : [], "saz");
      return true;
    case "file.save-selected":
      if (!selected.length) say(t("Select sessions first"), "error");
      else await saveArchive(selected, "saz");
      return true;
    case "file.export-har":
      await saveArchive(selected.length > 1 ? selected : [], "har");
      return true;
    case "file.export-curl": {
      const ids = selected.length ? selected : await api.viewIds(0, Math.min(get().listTotal, 500));
      const path = await save({ defaultPath: `quena_${stamp()}.sh`, filters: [{ name: t("Shell script"), extensions: ["sh"] }] });
      if (!path) return true;
      const parts = ["#!/bin/sh", "# Generated by Quena"];
      for (const sid of ids.slice(0, 500)) {
        const d = await api.detail(sid);
        if (!d || d.summary.kind === "tunnel") continue;
        const body = await snippetBody(d);
        parts.push(`# #${sid}`, buildCurl(d, body?.text ?? null, body?.bytes));
      }
      await api.writeTextFile(path, parts.join("\n\n") + "\n");
      say(t("cURL script written to {path}", { path }));
      return true;
    }
    case "file.save-response-body":
    case "file.save-request-body": {
      const sid = get().focusId;
      if (sid == null) return true;
      const part = id === "file.save-request-body" ? "request" : "response";
      const d = await api.detail(sid);
      if (!d) return true;
      const info = part === "request" ? d.requestBody : d.responseBody;
      const name = (d.request.url.split("?")[0].split("/").pop() || `body-${sid}`).replace(/[^\w.-]/g, "_");
      const path = await save({ defaultPath: name || `body-${sid}.bin` });
      if (!path) return true;
      const variant = get().settings?.decode && info.variants.includes("decoded") ? "decoded" : "raw";
      await api.saveBody(sid, part, variant, path);
      say(part === "request" ? t("Saving request body to {path}", { path }) : t("Saving response body to {path}", { path }));
      return true;
    }
  }
  return false;
}
